name: Deploy to GCP Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java 23
        uses: actions/setup-java@v3
        with:
          java-version: 23
          distribution: zulu # Use Temurin distribution of Java

      - name: Build with Maven
        run: mvn clean package

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT }}

      - name: Configure Docker
        run: gcloud auth configure-docker

      - name: Build Docker image
        run: docker build -t gcr.io/${{ secrets.GCP_PROJECT }}/your-spring-boot-app .

      - name: Push to Google Artifact Registry
        run: docker push gcr.io/${{ secrets.GCP_PROJECT }}/your-spring-boot-app

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy your-spring-boot-app \
            --image gcr.io/${{ secrets.GCP_PROJECT }}/your-spring-boot-app \
            --platform managed \
            --region ${{ secrets.GCP_REGION }} \
            --allow-unauthenticated
